spring:
  jpa:
    show-sql: true
  properties:
    dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
      format_sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  mvc:
    validation:
      enabled: true
  flyway:
    baseline-on-migrate: true
    url: jdbc:postgresql://localhost:5432/postgres
    user: postgres
    password: postgres
    schemas: postgres
    locations: classpath:db/migrations